### ISSUE TITLE
Import partials problem

### ISSUE THREAD

**Issue by Soularix** [dlmanning/gulp-sass#250] opened 2015-05-02 07:40 UTC
Hey, please when I import a partial in my main scss 
@import "layout/header";
I made my changes into the _header.scss
then I run gulp-sass it said : [gulp-sass] file to import not found or unreadable:

**Comment by Keats** [comment] 2015-05-02 11:23
Are you running the 2.x branch ?

**Comment by Soularix** [comment] 2015-05-02 13:14
2.x branch of what ?

**Comment by Keats** [comment] 2015-05-02 13:15
```
npm install dlmanning/gulp-sass#2.x
```

After removing gulp-sass from your node modules folder

**Comment by Soularix** [comment] 2015-05-02 16:01
I got an error while trying to install it

**Comment by Snugug** [comment] 2015-05-02 16:28
You should report installation issues to the node sass  issue queue

**Comment by Soularix** [comment] 2015-05-02 16:33
I installed the last version by : npm install gulp-sass@next --save-dev but I still have the same problem

**Comment by Soularix** [comment] 2015-05-03 09:43
I get this error : ←[90m  10:9←[39m  file to import not found or unreadable: layout/header

**Comment by Keats** [comment] 2015-05-07 10:07
gulp-sass 2.0 has been published to npm, please update to that and try to reproduce the issue

**Comment by Soularix** [comment] 2015-05-07 11:01
Now it's not even working lol

**Comment by Snugug** [comment] 2015-05-07 11:17
Duplicate of #235. Moving conversation there

**Comment by Keats** [comment] 2015-05-07 12:33
And closing this one

**Closed by Keats** 2015-05-07 12:33 UTC
