### ISSUE TITLE
Error "Invalid UTF-8" when compiling sass with @import in a directory whose parent has umlauts

### ISSUE THREAD

**Issue by wagich** [dlmanning/gulp-sass#322] opened 2015-08-06 13:27 UTC
This one is a bit peculiar:
Given the following directory structure:
* testä [note the umlaut]
  * styles
    * _import.scss
    * main.scss
  * gulpfile.js

I can compile `main.scss` sucessfully as long as I don't use `@import`. As soon as I import the partial `_import.scss` into `main.scss` I get the following error: `undefined:undefined  Invalid UTF-8`.

Having the stylesheet files in the root folder doesn't trigger the error. As soon as I remove the umlaut from the root folder name (renaming it to `test`) the error also disappears.

I'm using node.js 0.12.5, gulp-sass 2.0.4.
Using the node-sass CLI directly I can compile even when the folder name contains umlauts.

#### gulpfile.js
    var gulp = require("gulp");
    var sass = require('gulp-sass');
    
    gulp.task("sass", function () {
    	return gulp.src('./styles/main.scss')
    		.pipe(sass().on("error", sass.logError))
    		.pipe(gulp.dest("./styles/"));
    });
#### main.scss
    @import "import";
#### _import.scss
    body {
    	color: red;
    }

**Comment by raphaelparent** [comment] 2015-09-12 19:06
I have the same problem except that it's further in my path and it's actually something that I can't change easily. My path is `C:/Users/Propriétaire/[...]` . This is not my user and I don't get where it comes from, I cant rename the folder because it's locked.

**Comment by rayliao** [comment] 2015-10-23 09:19
I also have the same problem.

**Comment by madsravn** [comment] 2015-11-16 08:42
I experienced the same problem when I was trying to compile some a file where the absolute path of the scss file contained an 'ø'. When I changed the absolute path to contain nothing but English characters, it compiled fine.

**Comment by frio** [comment] 2015-11-16 22:52
Related to https://github.com/sass/node-sass/issues/716, which has been closed as Not Reproducible but that seems wrong...

**Comment by saper** [comment] 2015-11-17 22:19
@frio I am happy to re-open https://github.com/sass/node-sass/issues/716  if this gets reproduced with pure node-sass (javascript library or CLI) with a clean, minimal, self-contained example. This is because we have to work with the upstream library (https://github.com/sass/libsass) and it is quite likely I need to translate the testcase from JavaScript to C++.

I have just tried to generate CSS from SCSS in directories named "ä" and "ø", I was even able to generate a source map.

**Comment by wagich** [comment] 2015-12-07 08:42
It looks like there was some activity in https://github.com/sass/node-sass/issues/716, and a fix is currently waiting to be pulled into libsass (https://github.com/sass/libsass/pull/1774)

**Comment by saper** [comment] 2015-12-08 19:11
Is this problem occurring only on Windows?

**Comment by xzyfer** [comment] 2015-12-10 13:04
LibSass patch has been merged. I'll close this when the next LibSass version ships with gulp-sass.

**Comment by xzyfer** [comment] 2016-05-10 12:44
This has been fixed in v2.3.1.

**Closed by xzyfer** 2016-05-10 12:44 UTC
Labels: bug, libsass

**Comment by jamiehutber** [comment] 2016-11-15 15:34
I am receiving the same error.

Using a repo that was created on windows and now being used on ubuntu.

I am unsure if its the file or the folder structure. But I cannot see any odd characters in any of my folders.
    "gulp-sass": "^2.3.2"

**Comment by nickmarinho** [comment] 2017-06-23 19:28
I have a file called "principal.scss"
Inside this file I have a list of @import
My "gulp-sass": "^3.1.0".

My task = 
`gulp.task('sass', function () {
  return gulp.src('./source/sass/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('./dist/css'));
});`

Googling for 3 days and no fix for this error.
I'm not alone =)
