### ISSUE TITLE
Files that start with an underscore are ignored

### ISSUE THREAD

**Issue by irsick** [dlmanning/gulp-sass#256] opened 2015-05-07 15:43 UTC
I'm trying to build Bootstrap from it's official SASS repo https://github.com/twbs/bootstrap-sass.

All it's assets are prefixed by underscore
https://github.com/twbs/bootstrap-sass/tree/master/assets/stylesheets 

When I do something like this

```javascript
gulp.task('sass', function() {
  return gulp.src('./scss/_bootstrap.scss')
   .pipe(sass())
   .pipe(gulp.dest('./css/'));
});
```
Gulp runs task, does nothing and doesn't show any error.

# Workaround solution

The only one workaround solution I found is to create non-underscored init.scss with following content

```css
@import "bootstrap";
```
And run it in Gulp

```javascript
gulp.task('sass', function() {
  return gulp.src('./scss/init.scss')
   .pipe(sass())
   .pipe(gulp.dest('./css/'));
});
```

**Comment by Keats** [comment] 2015-05-07 21:49
This is normal behaviours, files starting with _ in sass are partials that do not render a file.
Using your first example would not result in any file being created, you can rename it to bootstrap.scss and it will work

**Comment by Keats** [comment] 2015-05-08 12:08
Closing as this is intended behaviour.
You are supposed to import bootstrap (or individual modules) in your own sass files like you did in the init.scss

**Closed by Keats** 2015-05-08 12:08 UTC
