### ISSUE TITLE
gulp-util is deprecated

### ISSUE THREAD

**Issue by kuangyeheng** [dlmanning/gulp-sass#651] opened 2018-01-09 15:39 UTC
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

Hope to fix it! thanks

**Comment by simonua** [comment] 2018-01-10 10:35
Hi @kuangyeheng, this would be a duplicate of #646, I believe. I think you can close this issue and amend #646 instead.

**Closed** 2018-01-10 15:45 UTC
