### ISSUE TITLE
not working with gulp 4.0

### ISSUE THREAD

**Issue by TeodorKolev** [dlmanning/gulp-sass#383] opened 2015-10-31 15:02 UTC
Task did not finish Starting gulpSass...

```javascript

var gulp = require('gulp');
var sass = require('gulp-sass');

var paths = {
  sass:    'src/css/**/*.scss',
 };
gulp.task('sass', function () {
  return sass(paths.sass)
    .on('error', sass.logError)
    .pipe(gulp.dest('src/css'));
});
function watch() {
  livereload.listen();
  ...
  gulp.watch(paths.sass, sass);
}

gulp.task('build',  gulp.parallel(sass, ... watch));

gulp.task('default', gulp.series('build'));
```

**Comment by Keats** [comment] 2015-10-31 15:11
You need to use gulp.src, here's the task I've been using with gulp 4 for months now

```js
var sassFiles = "src/style/**/*.scss"

gulp.task("sass", function() {
  return gulp.src(sassFiles)
    .pipe(sass({outputStyle: "compressed"}).on("error", sass.logError))
    .pipe(autoprefixer())
    .pipe(gulp.dest(outputFolder))
});
```

**Comment by TeodorKolev** [comment] 2015-10-31 15:16
That makes absolute no difference.

**Comment by TeodorKolev** [comment] 2015-10-31 16:39
Plsease test and don't close issues like that
```javascript
'use strict';
 
var gulp = require('gulp');
var sass = require('gulp-sass');
 
gulp.task('sass', function () {
  gulp.src('src/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('dist/css'));
});
 
gulp.task('sass:watch', function () {
  gulp.watch('src/**/*.scss', ['sass']);
});


gulp.task('build', gulp.series(
  gulp.parallel(sass)
));

gulp.task('default', gulp.series('build'));
```

**Comment by Keats** [comment] 2015-10-31 18:39
The above works for me (minus the gulp 4 incompatibility: gulp.watch('src/**/*.scss', ['sass']); ).

I've tried on one of my repo (https://github.com/Keats/snowflake) and I don't get any error and everything finishes correctly. Let me know if my repo works for you and otherwise please provide a sample repo that reproduces the error

**Comment by robertbaker** [comment] 2015-11-02 23:53
@Keats been using this with gulp 4 and it works fine. This is an issue with his tasks.

@TeodorKolev 

this is wrong

```
gulp.task('build', gulp.series(
  gulp.parallel(sass)
));

```
should be 

```
gulp.task('build', gulp.series('build, 'watch:sass'));

```

and
```
gulp.task('sass', function () {
  gulp.src('src/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('dist/css'));
});
```

should be

```
gulp.task('sass', function () {
  return gulp.src('src/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('dist/css'));
});
```

You need to have `return` for tasks that do not run async.

@Keats You can close this, this is an issue with his gulp tasks.

**Comment by Zork33** [comment] 2015-11-13 18:29
I’ve being using gulp-sass since Apr 2015, and it perfectly worked with up to NodeJS 0.2.12  Once I’ve switched to NodeJS 4.2.2 – I’ve faced with very close problem.  Gulp-sass tasks starts and then nodejs stop working.

To be clear, I've made a test based on a code from this thread.  It’s CoffeeScript:

```
gulp = require 'gulp'
sass = require 'gulp-sass'

sassFiles = './src/sass/**/*.sass'

gulp.task 'default', (->
  return gulp.src(sassFiles)
  .pipe(sass(outputStyle: "compressed").on("error", sass.logError))
  .pipe(gulp.dest('./build')))
```

and this what I see in console:

```
C:\Work\TestProj>gulp
[21:21:38] Using gulpfile C:\SVN\_WebProfyManagement\gulpfile.js
[21:21:38] Starting 'default'...
C:\Work\TestProj>
```

I'm working on Window7 x64.  Could that be a problem?

Any idea how I could get more details from nodejs why gulp-sass kills it?

**Comment by Zork33** [comment] 2015-11-14 05:39
I’ve found specific reason why my nodejs 4.2.2 was crashing with my sass files.  It was the fact that I was calling Susy @include container prior of calling @include layout.  And now gulp-sass perfectly works for me on NodeJS 4.2.2.  So, my issue is closed

In general, it’s still interesting why sass code can silently crash nodejs.  I believe this question is for node-sass project.

**Comment by xzyfer** [comment] 2015-11-14 17:01
Could you please create a sample sass file I can test with. We should fix
this crash in LibSass.

**Comment by Zork33** [comment] 2015-11-15 08:13
https://github.com/Zork33/libsass-bug - simple project that demonstrates the problem

**Comment by JimBobSquarePants** [comment] 2015-11-18 02:30
@xzyfer 

Using concatenation rather than interpolation can cause it to crash out also.  

Bad

    background: url($img-url + "/icons/icon-play.png") 0 0 no-repeat;

Good

    background: url("#{$img-url}/icons/icon-play.png") 0 0 no-repeat;

**Comment by xzyfer** [comment] 2015-11-19 10:24
@JimBobSquarePants good news this appears to be fixed. Try the latest node-sass.

**Comment by xzyfer** [comment] 2015-11-19 10:40
@Zork33 I can confirm this does segfault. Unable to create a reduced test cases of yet.

**Comment by xzyfer** [comment] 2015-11-19 10:54
@Zork33 OK I have a minimal reproduction now. Thanks heaps for creating that repo!

```
@mixin foo($bar...) {
  @each $item in $bar {
  }
}

@include foo(());
```

I believe this a duplicate of https://github.com/sass/libsass/issues/1709

**Comment by JimBobSquarePants** [comment] 2015-11-19 11:09
Thanks @xzyfer . Great to hear!

**Comment by loganhenson** [comment] 2015-11-23 16:51
@TeodorKolev I wanted to post the actual issue (in case you hadn't resolved it)..

You are actually calling gulp-sass (the npm module, which is not a gulp task) directly, instead of the sass task. Try naming you sass task something different and it will complete properly. Hope that helps anyone who made the same mistake and ends up here!

**Comment by fyddaben** [comment] 2015-11-27 02:55
i have the same question .start sass .and never finished

**Comment by fyddaben** [comment] 2015-11-27 03:36
i update my node-sass to 3.2.5 . and slove it .  It waste one night time......

**Comment by glen-84** [comment] 2015-12-11 10:01
Why is this issue still open?

**Comment by glen-84** [comment] 2015-12-11 10:05
Actually, the code in the README needs to be updated, as it doesn't return the stream.

**Comment by xzyfer** [comment] 2015-12-11 12:39
We're open to pull requests.

**Comment by Keats** [comment] 2015-12-11 13:03
#408 should solve that

**Comment by glen-84** [comment] 2015-12-11 13:12
Ah, I forgot about your PR. So this can be closed then?

**Closed** 2015-12-21 11:00 UTC
