### ISSUE TITLE
Update node-sass to >= 3.11 to support Node 7

### ISSUE THREAD

**Issue by jGleitz** [dlmanning/gulp-sass#560] opened 2016-11-16 17:05 UTC
See https://github.com/sass/node-sass/issues/1766

**Comment by xzyfer** [comment] 2016-11-16 22:53
`^3.4.2` includes 3.10.1. You can learn more about semver at https://github.com/npm/node-semver#caret-ranges-123-025-004.

In future please search to existing issues before opening new one. Duplicate of #491 #493 #489 #487 #494 #504 #547 #550 #557

**Closed** 2016-11-16 22:53 UTC
