### ISSUE TITLE
Sourcemaps Path Incorrect

### ISSUE THREAD

**Issue by ajmueller** [dlmanning/gulp-sass#300] opened 2015-06-18 20:49 UTC
We use gulp-sass and gulp-sourcemaps on an open source framework called [Phoenix](https://github.com/connectivedx/Phoenix/) and are currently prepping a new release.  Updating gulp-sass from 1.3.3 to 2.0.1 introduced an issue where the path to source SCSS files for gulp-sourcemaps are missing a directory.

**1.3.3**:
![image](https://cloud.githubusercontent.com/assets/1442179/8241809/4b84a8c0-15c0-11e5-8460-e2df5df5a7b1.png)

**2.0.1**:
![image](https://cloud.githubusercontent.com/assets/1442179/8241813/50467dd4-15c0-11e5-81c4-7d39275af6b9.png)

Note that as of gulp-sass 2.0.1 the `css` directory is missing from the path, thereby loading empty files in the Chrome inspector.  Is this an issue with gulp-sourcemaps or gulp-sass?  If you need additional details or information about how to get our code up and running locally to see for yourself, let me know.

I've posted this issue [on gulp-sourcemaps as well](https://github.com/floridoo/gulp-sourcemaps/issues/133).

**Comment by austinpray** [comment] 2015-06-18 21:47
Pretty sure this fixes it: https://github.com/dlmanning/gulp-sass/pull/286

Can you confirm?

**Comment by Snugug** [comment] 2015-06-24 11:24
What does your pipe stream look like?

**Comment by ajmueller** [comment] 2015-06-27 15:57
Here's our pipe stream:

https://github.com/connectivedx/Phoenix/blob/master/Assets/src/build/drivers/css.js

cc @elseloop

**Comment by stevenjlho** [comment] 2015-07-04 18:02
I have same issue. I  compile sass to css only, the issue still occur.

**Comment by TheDutchCoder** [comment] 2015-07-12 22:46
Same issue here, I also get completely random references to partials.

E.g. the class ".btn", only found in "theme/objects/_btn.scss" when inspected shows references to "_typography", "_forms", etc.

Completely unrelated files :)

**Comment by Nirazul** [comment] 2015-07-17 20:04
Yep, same issue `sources` array is empty.

**Comment by Nirazul** [comment] 2015-07-21 13:49
Maybe this helps anyone. I've finally figured out, how to fix the empty sourcemap files by using `sourceRoot` as a function.

I have the following setup:

**files:**
```
main-file 1: <src-dir>/src/scss/app/main.scss
main-file 2:  <src-dir>/src/scss/utils/utils.scss
```

**pipe stream**
```
return gulp.src('**/*.scss',
    { cwd: '<src-dir>/scss' }
)
    .pipe( sourcemaps.init() )
    .pipe( sass() )
    .pipe( sourcemaps.write('.', {
        includeContent: true,
        sourceRoot: function(file) {
            var dir = path.dirname(file.relative);
            return path.join('<src-dir>', 'scss', dir);
        }
    }) )
    .pipe( filterMap.restore({ end: true }) )
    .pipe( gulp.dest('<dist-dir>/scss/dist') );
```

The underlying problem is that `gulp-sourcemaps` usese `file.base` when no `sourceRoot` is provided. `file.base` is not necessarily the directory the source files are in. So I needed to correct the sourceRoot according to the current main file.

This may not be the cause for everyone's problems here, as the problems described in this issue thread are different from each other.

**Comment by martinoconnor** [comment] 2015-08-06 15:07
This issue might be duplicated by #319

**Comment by Keats** [comment] 2015-12-02 17:10
Closing as there is #394 which is more recent

**Closed by Keats** 2015-12-02 17:10 UTC
Labels: more info needed, question, sourcemaps
