### ISSUE TITLE
Gulp-sass hangs after an error occurred

### ISSUE THREAD

**Issue by sqal** [dlmanning/gulp-sass#243] opened 2015-04-20 09:40 UTC
I have installed gulp-sass 2.0.0-alpha.1 and I am having following problem. My sass config:

```
var paths = {
    styles: {
        src: 'app/styles/**/*.scss',
        dest: '.tmp/css'
    }
};

gulp.task('styles', function() {
    return gulp.src(paths.styles.src)
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest(paths.styles.dest))
    .pipe(reload({ stream: true }));
});
```

and when I accidentally use some variable that is not defined (or do any error, missing semicolon for example), then of course i am getting an error in the console:

`
[11:23:52] [gulp-sass] app\styles\elements\_buttons.scss
  54:12  Undefined variable: "$color".
`

but that's it. Gulp-sass now hangs out and does not respond to further changes. I have to stop gulp task and run it again. Did I do something wrong with my configuration or the problem lies somewhere else?

**Comment by Snugug** [comment] 2015-04-22 10:44
Duplicate of #90

**Closed by Snugug** 2015-04-22 10:44 UTC
