### ISSUE TITLE
watch stops on error

### ISSUE THREAD

**Issue by jenil27** [dlmanning/gulp-sass#261] opened 2015-05-09 04:21 UTC
This is how my task looks like

```
gulp.src(config.sassPath + '/*.scss') .pipe(sass({ 
                outputStyle: 'expanded',
                includePaths: styles
            }) .on('error', sass.logError))
            .pipe(gulp.dest('./public/css'))
            .pipe(filter('**/*.css')) // Filtering stream to only css files
            .pipe(browserSync.reload({
                stream: true
            })); 
```

I need to restart gulp whenever an error occurs.

**Comment by Keats** [comment] 2015-05-09 09:05
could you provide an example repo for that issue please?

**Comment by antleblanc** [comment] 2015-05-09 11:48
I just created a example repository for that.
I hope it's suitable to illustrate that issue

**Comment by Snugug** [comment] 2015-05-09 15:04
Duplicate of #90. Please refer to that issue to help resolve your problem using the provided working solutions.

**Closed** 2015-05-09 15:07 UTC
