### ISSUE TITLE
Problem with gulp-sourcemaps 

### ISSUE THREAD

**Issue by adamrecsko** [dlmanning/gulp-sass#244] opened 2015-04-21 15:13 UTC
I used this versions:
* gulp-sass: 2.0.0-alpha.1
* gulp: 3.8.11
* gulp-sourcemaps: 1.5.2
      
I tried the alpa.1 of gulp-sass and if I import another scss file in the app.scss file I get an error but only if I try to apply sourcemaps. Without sourcemaps it works fine.

```
return gulp.src('./app.scss')
         .pipe(sourcemaps.init())
         .pipe(sass())
         .pipe(sourcemaps.write())
         .pipe(gulp.dest('./'));
```

The error I got:

```
gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/array-set.js:83
    throw new Error('No element indexed by ' + aIdx);
          ^
Error: No element indexed by -1
    at ArraySet_at [as at] (node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/array-set.js:83:11)
    at SourceMapConsumer_parseMappings [as _parseMappings] (node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:229:44)
    at SourceMapConsumer.Object.defineProperty.get (node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:164:14)
    at SourceMapConsumer_eachMapping [as eachMapping] (node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:547:24)
    at Function.SourceMapGenerator_fromSourceMap (node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-generator.js:52:26)
    at applySourceMap (node_modules/gulp-sass/node_modules/vinyl-sourcemaps-apply/index.js:22:40)
    at filePush (node_modules/gulp-sass/index.js:80:9)
    at Object.callback (node_modules/gulp-sass/index.js:117:9)
    at options.success (node_modules/gulp-sass/node_modules/node-sass/lib/index.js:278:32)

```

**Comment by Snugug** [comment] 2015-04-21 15:40
Duplicate of #241

**Closed by Snugug** 2015-04-21 15:40 UTC
