### ISSUE TITLE
overwriting z-index in --production

### ISSUE THREAD

**Issue by OskHa** [dlmanning/gulp-sass#432] opened 2016-01-25 22:36 UTC
Hi, i hope this is the right place to submit an issue.

after running `gulp --production` sass ignores my `z-index` and sets whatever it wants leads to some UX problems.

Bug found while using following stack:
- elixir
- angular
- angular material ...

**Comment by Keats** [comment] 2016-01-25 22:41
I'm not entirely sure what the issue is but I'm pretty sure that this is not a gulp-sass issue

**Comment by OskHa** [comment] 2016-01-25 22:51
i will try to get more info. maybe its referencing to the elixir. but still this is very strange.

every time i set f.i. `.some-class { z-index: 99 }` after gulp in production i see `z-index: 19` or 18. like sass was trying to calculate the indexes on its own.

**Comment by Keats** [comment] 2016-01-25 23:02
There's no production tag in gulp so that's probably something on one of your frameworks in the middle

**Comment by HarveyWilliams** [comment] 2016-01-28 11:29
Turns out this occurs if you use cssnano in the pipe.

Using cssnano as:
`.pipe(cssnano({ zindex: false }))`

fixes the zindex changing.

[http://cssnano.co/optimisations/#optimise-z-index-unsafe-](http://cssnano.co/optimisations/#optimise-z-index-unsafe-)

**Comment by yattias** [comment] 2016-03-05 21:54
@HarveyWilliams thanks for this. Had the same issue. Weird that they would have an unsafe flag on as default.

**Comment by miltonhowe** [comment] 2016-04-10 13:51
@yattias @HarveyWilliams thank you and agreed - this cost me a couple of hours. Great option - but save it for people who want to tinker.

**Comment by xzyfer** [comment] 2016-04-10 22:08
Thanks for your investigating @harveywilliams. Closing this since it's not a gulp-sass issue

**Closed by xzyfer** 2016-04-10 22:08 UTC
